### ISSUE TITLE
5.3 小节中给出的最佳实现代码中 is_chief 的赋值位置错误

### ISSUE THREAD

**Issue by 777Arch** [DjangoPeng/tensorflow-in-depth#2]
`is_chief = (FLAGS.task_index == 0)` 是否应该放在 312 行之前？

**Comment by DjangoPeng** [comment]
谢谢你的建议。如果重印时采纳了你的建议。我们会显式致谢！

**Comment by DjangoPeng** [comment]
刚刚查看了下。这行代码是用来判断当前的 task 是否为 chief task，放在这里没有问题哈。

**Comment by DjangoPeng** [comment]
你指的应该是 5.2节 的最佳实践吧？如果是的话，那个 bug 我刚刚更新了，下次印刷会修复。谢谢你的建议！
Ref: #5
