### ISSUE TITLE
4.1 小节读取cifar示例代码不全

### ISSUE THREAD

**Issue by anxingle** [DjangoPeng/tensorflow-in-depth#4]
无论是书上的，还是github的，代码中相当多的变量未定义就使用。 4.1_best_practice.py 中36行label_bytes哪里定义了？ 41行IMAGE_DEPTH_major也没有...

**Comment by DjangoPeng** [comment]
我们最近重印的一版已修改了此段代码示例，之前校稿时没有查出错误，非常抱歉！感谢您的建议！

**Comment by anxingle** [comment]
....   
重印了 🤣 那勘误是不是需要发出来啊，而且也需要同步最新的tf奥。

**Comment by DjangoPeng** [comment]
你好，因为之前校稿时出现了版本错误，所以导致了这个问题。
最新一批印刷会修复 4.1_best_practice.py 这个文件的错误。

关于 TensorFlow 版本更新，这个无法通过重印解决。经过和人民邮电出版社的沟通，可能会在明年根据 TF 2.0更新这本书，到时候可以用 tf.data 这个模块来解决 Data I/O 的问题，不再需要之前流水线这套复杂的实现了。

**Comment by DjangoPeng** [comment]
PTAL：https://github.com/DjangoPeng/tensorflow-in-depth/blob/master/code/4_data_io/4.1_best_practice.py
